### ISSUE TITLE
Nombre de réponse lors d'une recherche

### ISSUE THREAD

**Issue by NerOcrO** [ansforge/IG-essais-cliniques#15]
## Description du problème
Il est écrit `Le service développé renvoie les 200 premiers résultats` ce qui me semble beaucoup car cela peut provoquer une certaine latence.

## Fichier•s concerné•s
https://ansforge.github.io/IG-essais-cliniques/ig/main/st_flux1.html#r%C3%A9ponse-de-base--succ%C3%A8s

## Solution proposée
J'ai implémenté juste 20 résultats par défaut, est-ce ok ?

D'ailleurs, je me pose la question de la pertinence du filtre `_count`, j'ai pris partie de ne pas l'implémenter pour le moment car je trouve que c'est la porte ouverte à des problèmes.
Si quelqu'un demande 100 000 essais cliniques, le serveur risque de tomber. Est-ce que l'on doit tenir ce genre de charge ?

A discuter.

**Comment by sly-kereval** [comment]
Sujet à discuter en fonction du besoin, lors du prochain point (21/07).

**Comment by sly-kereval** [comment]
Réunion 21/07 : 

Pour l'instant, il a été décidé de fixer la valeur maximale à 5000 (tests nécessaires pour valider) et de fixer la valeur par défaut à 20 si l'utilisateur ne renseigne pas le champ _count.

**Comment by NerOcrO** [comment]
C'est en production
