### ISSUE TITLE
Pays de recrutement 

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-essais-cliniques#19]
## Description du problème

Dans son mail du 12/07/2023, Octo demande où se trouve le pays de recrutement en FHIR. 

## Solution proposée

Il y a deux possibilités : 
- Utiliser l’élément site, de type Location (élément address.country)
- Créer une extension dans Researchstudy (ce choix peut être justifié par le fait qu’en R5, un élément « region » est dédié à cette information)

**Comment by sly-kereval** [comment]
Réunion 21/07 : 

Dans les [recommandations de l'OMS](https://www.who.int/clinical-trials-registry-platform/network/who-data-set), un champ est dédié au pays de recrutement. 
De plus, il est possible que le champ "pays de recrutement" soit renseigné mais pas celui "site de recrutement", ce sont des données décorrélées. 

Ces éléments penchent donc en faveur de la seconde solution.

**Comment by sdemeyANS** [comment]
il faut donc faire une extension
on peut faire une extension type http://hl7.org/fhir/researchstudy-definitions.html#ResearchStudy.region donc

**Comment by sdemeyANS** [comment]
@sly-kereval on peut pas utiliser ça plutôt ? https://ansforge.github.io/IG-essais-cliniques/ig/sd-concept-map-statut-de-lessai/StructureDefinition-eclaire-researchstudy-definitions.html#ResearchStudy.location
?

**Comment by sly-kereval** [comment]
> @sly-kereval on peut pas utiliser ça plutôt qui est natif ? http://hl7.org/fhir/R4/researchstudy-definitions.html#ResearchStudy.location ?

Si en effet !  On est passé à côté ...

**Comment by sdemeyANS** [comment]
ok je te laisse mettre à jour le mapping. je peux ajouter "short" pour donner la définition "pays de recrutement" pour cet élément dans le profil
