### ISSUE TITLE
Jeu de valeur du statut de l'essai 

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-essais-cliniques#22]
## Description du problème

Concernant le statut de l'essai, l'élément FHIR status impose un [valueset](http://hl7.org/fhir/R4/valueset-research-study-status.html) (binding : Required) qui ne correspond pas exactement aux valeurs ECLAIRE.

## Solution proposée
 
Suite à plusieurs discussions, le mapping suivant est proposé : 

| **ECLAIRE** | **FHIR** | **Définition FHIR** |
| --------------- |---------------|---------------|
| A démarrer | approved |  Protocol is approved by the review board. |
| En cours | active |  Study is opened for accrual. |
| Suspendue  | temporarily-closed-to-accrual, temporarily-closed-to-accrual-and-intervention | Study is temporarily closed for accrual; can be potentially resumed in the future; patients can be examined and treated...  |
| Prolongée - prorogée (= à démarrer) | approved |  Protocol is approved by the review board. |
| Expirée (étude qui a été validée mais qui n’a jamais commencée) | approved | Protocol is approved by the review board. |
| Terminée  | completed | Study is closed to accrual and intervention, i.e. the study is closed to enrollment, all study subjects have completed treatment or intervention but are still being followed according to the primary objective of the study. |
| Terminée (fin anticipée) |  administratively-completed  |  Study is completed prematurely and will not resume; patients are no longer examined nor treated. |
| Archivée | completed |   Study is closed to accrual and intervention, i.e. the study is closed to enrollment, all study subjects have completed treatment or intervention but are still being followed according to the primary objective of the study. |
| Abandonnée | completed | Study is closed to accrual and intervention, i.e. the study is closed to enrollment, all study subjects have completed treatment or intervention but are still being followed according to the primary objective of the study. |
| _Rapatriée vers le CTIS_ | _A supprimer_ |  |

**Comment by NerOcrO** [comment]
Il y a aussi abandonnée/completed que nous avions oublié.
Notre définition : on ne sait pas pourquoi l'étude est abandonnée, ça peut aussi être un problème de recrutement ou de financement.

**Comment by nriss** [comment]
- [ ] Créer un CodeSystem custom avec les valeurs possibles ECLAIRE
- [ ] Créer une ConceptMap pour indiquer le mapping entre les JDV ECLAIRE et le ValueSet FHIR required

**Comment by sly-kereval** [comment]
Ajout de la valeur "Abandonnée" (= "completed") suite à la réunion du 21/07.

**Comment by sdemeyANS** [comment]
> * [ ]  Créer un CodeSystem custom avec les valeurs possibles ECLAIRE
> * [ ]  Créer une ConceptMap pour indiquer le mapping entre les JDV ECLAIRE et le ValueSet FHIR required

@NerOcrO @cbihanANS et à voir si c'est nécessaire pour le MVP en terme de priorité ? (@nriss pour info)

**Comment by sdemeyANS** [comment]
"abandonnée" équivalence ValueSet fhir [withdrawn](http://hl7.org/fhir/R4/codesystem-research-study-status.html#research-study-status-withdrawn) ?

**Comment by sdemeyANS** [comment]
proposition https://ansforge.github.io/IG-essais-cliniques/ig/sd-concept-map-statut-de-lessai/ConceptMap-eclaire-study-status-concept-map.html

**Comment by sdemeyANS** [comment]
> > * [ ]   Créer un CodeSystem custom avec les valeurs possibles ECLAIRE
> > * [ ]   Créer une ConceptMap pour indiquer le mapping entre les JDV ECLAIRE et le ValueSet FHIR required
> 
> @NerOcrO et @cbihanANS à voir si c'est nécessaire pour le MVP en terme de priorité ? (@nriss pour info)

du coup j'ai construit une proposition. donc on peut l'embarquer si cela vous convient
