### ISSUE TITLE
Jeu de valeur phase de l'essai

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-essais-cliniques#23]
## Description du problème

Dans son mail du 12/07, Octo indique concernant la phase de l'essai : 
Pour le CTIS il s’agit bien d’une phase 1 2 ou 3, donc qui peut être qualifié. Mais pour la réglementation JARDE on a phase précoce oui ou non (donc pas forcément qualifiable de codable concept).

## Solution proposée

Dans le [JDV FHIR](https://hl7.org/fhir/R4/valueset-research-study-phase.html), il y a les valeurs « early-phase-1 » ou « NA », est-ce que cela pourrait correspondre pour « précoce » ? 
Si le JDV FHIR n’est pas adapté, il est possible de créer un JDV spécifique.

**Comment by sly-kereval** [comment]
Le JDV FHIR convient, en utilisant "NA" pour "précoce".

**Comment by sly-kereval** [comment]
Le binding du JDV FHIR est "Example", il est donc possible de créer, si besoin, un nouveau valueset contenant les valeurs du JDV FHIR et de nouvelles valeurs (notamment phase-3-phase-4).

La liste des valeurs est à valider côté métier.

**Comment by sdemeyANS** [comment]
Il faut donc : 

- [ ] ajouter la valeur manquante dans la jdv https://hl7.org/fhir/R4/valueset-research-study-phase.html
- [ ] créer la concepmap et le codesystem pour faire la correspondance ECLAIRE/FHIR pour plus de lisibilité

**Comment by sdemeyANS** [comment]
> Il faut donc :
> 
> * [x]  ajouter la valeur manquante dans la jdv https://hl7.org/fhir/R4/valueset-research-study-phase.html
> * [ ]  créer la concepmap et le codesystem pour faire la correspondance ECLAIRE/FHIR pour plus de lisibilité

Je traite que le 1er point pour le mvp
