### ISSUE TITLE
Que veut dire Complex ?

### ISSUE THREAD

**Issue by NerOcrO** [ansforge/IG-essais-cliniques#43]
## Description du problème
Pour la création de `ECLAIRELabel`, il est écrit que c'est un `Complex` mais ce n'est pas un objet FHIR.
Nous avons donc fait ce qui s'en rapproche le plus, une simple extension.

## Solution proposée
Est-ce correct ?
Ou bien, pouvez vous préciser ce que c'est exactement au sens FHIR ?

**Comment by sdemeyANS** [comment]
Bonjour,
Cela indique que l'extension est complexe
