### ISSUE TITLE
ECLAIREReviewDate en instant ?

### ISSUE THREAD

**Issue by NerOcrO** [ansforge/IG-essais-cliniques#45]
## Description du problème
La date de l'extension `ECLAIREReviewDate` est de type `date`.

## Solution proposée
Nous proposons de mettre plutôt un type `instant` comme la date de révision technique pour garder une consistence.

**Comment by sly-kereval** [comment]
En effet, la solution proposée semble plus cohérente. Ok pour toi @sdemeyANS ?
