### ISSUE TITLE
INDISPONIBLE ou supprimer l'objet FHIR

### ISSUE THREAD

**Issue by NerOcrO** [ansforge/IG-essais-cliniques#46]
## Description du problème
Pour rappel, nous avons pris le partie de mettre le mot `INDISPONIBLE` quand la donnée n'existe pas encore côté SI RIPH mais qu'elle devrait être là à terme (en attente de dev).
Ensuite, nous nous sommes aperçu que le validator ne veut pas de valeur vide (comprendre chaine de caractère vide). Ce n'est pas un bug, c'est juste que le déposant n'a pas remplie cette donnée. Nous avons pris le partie de remplacer par le mot `NULL`.

## Discussion
Est-ce que nous laissons comme ça ? (c'est ce qui est en production actuellement)
OU
Est-ce que nous faisons tout le contraire, c'est-à-dire, n'afficher que les données présentes ?

**Comment by sdemeyANS** [comment]
Bonjour,
Je pense qu'il ne faut diffuser que les données présentes

**Comment by sly-kereval** [comment]
Décision Weekly 28/08/2023 : 

La valeur `INDISPONIBLE` est conservée pour les données inexistantes actuellement mais qui le seront par la suite, pour être plus explicite. Par contre, les données non renseignées ne sont pas renvoyées. 

Cette décision est à transmettre à Santé.fr, pour qu'ils aient les informations nécessaires pour interpréter les données.
