### ISSUE TITLE
Erreur du validator sur la tranche d'âge

### ISSUE THREAD

**Issue by NerOcrO** [ansforge/IG-essais-cliniques#47]
## Description du problème
La validator nous rapporte l'erreur suivante :
`The property comparator must be a JSON Array, not a Primitive property (at Bundle.entry[0].resource.contained[0].characteristic[1].value[x].low)`
Alors que le data type [Quantity](https://www.hl7.org/fhir/r4/datatypes.html#Quantity) a bien comme champ `comparator` une chaine de caractère.

## Exemple
```json
{
  "code": {
    "coding": [
      {
        "display": "INDISPONIBLE"
      }
    ],
    "text": "Group characteristic code"
  },
  "valueRange": {
    "low": {
      "comparator": ">=",
      "unit": "years",
      "value": 65
    }
  },
  "exclude": false
}
```

Qu'est-ce qui cloche ?

**Comment by sly-kereval** [comment]
Vous utilisez "valueRange" qui est de type Range, je pense qu'il faut plutôt utiliser "valueQuantity".

**Comment by sly-kereval** [comment]
Le type de données [Range](http://hl7.org/fhir/R4/datatypes.html#Range) a 2 éléments, `low` et `high`, de type [SimpleQuantity](http://hl7.org/fhir/R4/datatypes.html#SimpleQuantity) pour lequel le `comparator` ne peut pas être utilisé.

Concernant la tranche d'âge, si on utilise `Range`, il n'est pas nécessaire d'avoir un comparateur car les éléments `low ` et `high` permettent de renseigner la valeur minimale et la valeur maximale. 

Dans le cas de l'exemple qui remonte une erreur, si on enlève le comparateur, l'information transmise est tout de même valide. En effet, cela signifie que la borne minimale de l'âge des participants est 65 ans.

**Comment by NerOcrO** [comment]
C'est corrigé et en production.
