### ISSUE TITLE
phase de l'essai = creation conceptMap

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-essais-cliniques#48]
créer la concepmap et le codesystem pour faire la correspondance ECLAIRE/FHIR pour plus de lisibilité (suite issue #23

**Comment by NerOcrO** [comment]
C'est une donnée que nous n'avons pas encore mais qu'il y aura à terme donc oui, cette phase doit apparaître.

**Comment by sdemeyANS** [comment]
voici le résultat proposé pour cette ConceptMap https://ansforge.github.io/IG-essais-cliniques/ig/main/ConceptMap-eclaire-study-phase-concept-map.html
