### ISSUE TITLE
Ajouter une précision liée à la réglementation

### ISSUE THREAD

**Issue by NerOcrO** [ansforge/IG-essais-cliniques#52]
## Description du problème

Ajouter une précision liée à la réglementation au plus près de la régulation.

## Solution proposée

Il faut un champ :
- "catégorie" pour Jardé
- "intervention" pour CTIS
- "cas" pour DM/DMDIV

![image](https://github.com/ansforge/IG-essais-cliniques/assets/4953365/6ce84225-bb24-4b63-9385-cb48a25b994c)

**Comment by sly-kereval** [comment]
Actuellement, l'attribut natif FHIR `category` est mappé sur le type d'essai, est-ce que cet élément peut correspondre aux champs demandés ou est-ce qu'il s'agit d'informations supplémentaires ?

**Comment by NerOcrO** [comment]
Ca nous va, c'est en production.

**Comment by sdemeyANS** [comment]
lié à #59

**Comment by paulineheurtebise** [comment]
Issue close car sera traitée dans la #59
