### ISSUE TITLE
Est-ce que l'on implémente le paramètre_include ?

### ISSUE THREAD

**Issue by NerOcrO** [ansforge/IG-essais-cliniques#64]
## Description du problème
Aujourd'hui, nous avons 4 références :
- enrollment
- site
- sponsor
- ECLAIRESecondarySponsor

Ce qui se traduit en FHIR de ne pas afficher la donnée directement, il faut la demander.
Par conséquent il faut ajouter le paramètre `_include` dans l'URL pour avoir la donnée.

Voici un exemple donné par HAPI :
```json
{
  "resourceType": "Bundle",
  "type": "searchset",
  "link": [ {
    "relation": "self",
    "url": "https://hapi.fhir.org/baseR4/ResearchStudy/_search?_include=*"
  }, {
    "relation": "next",
    "url": "https://hapi.fhir.org/baseR4?_getpages=3aac3b79-c8bc-484d-92c1-015e04ea0c50&_getpagesoffset=20&_count=20&_pretty=true&_include=*&_bundletype=searchset"
  } ],
  "entry": [
    {
      "fullUrl": "https://hapi.fhir.org/baseR4/ResearchStudy/71530",
      "resource": {
        "resourceType": "ResearchStudy",
        "id": "71530",
        "title": "Lollipop 1 Study",
        "sponsor": {
          "reference": "Organization/71575"
        },
        "principalInvestigator": {
          "reference": "Practitioner/72502"
        }
      },
      "search": {
        "mode": "match"
      }
    },
    {
      "fullUrl": "https://hapi.fhir.org/baseR4/Organization/71575",
      "resource": {
        "resourceType": "Organization",
        "id": "71575",
        "name": "Yorkshire Lollypop Research",
        "alias": [ "YLPR" ]
      },
      "search": {
        "mode": "include"
      }
    },
    {
      "fullUrl": "https://hapi.fhir.org/baseR4/Practitioner/72502",
      "resource": {
        "resourceType": "Practitioner",
        "id": "72502",
        "gender": "female",
        "birthDate": "1971-11-07"
      },
      "search": {
        "mode": "include"
      }
    }
  ]
}
```
Comme on peut le voir, au début de `entry`, il y a les documents demandés (ici qu'un pour l'exemple) puis les informations des références dans un ordre quelconque.
Du coup, en terme d'expérience développeur, ce n'est pas idéal parce qu'il va falloir boucler beaucoup pour reconstruire un essai clinique ce qui peut freiner l'adoption de l'API ECLAIRE.

## Questions à débattre

- Est-ce que ce format est obligatoire ? Ne pourrait-on pas remplacer les références directement dans l'essai clinique ?
- Pourquoi finalement avoir des références ? Car l'intention d'ECLAIRE est de délivrer des essais clinique et non pas une galaxie de ressources

Tout ceci pour simplifier les développements et l'expérience développeur.

**Comment by paulineheurtebise** [comment]
- Références 

Une ressource en FHIR représente un objet clinique ou administratif. 
Les ressources comme ResearchStudy peuvent contenir des références à d'autres ressources, qui représentent elles - mêmes un objet clinique ou administratif. 
Deux parties de la spécification aborde le fait d'inclure les informations directement à l'intérieur de la ressource : 
https://www.hl7.org/fhir/references.html#contained
https://www.hl7.org/fhir/domainresource.html#contained
Ce qui est expliqué c'est que cela est possible dans des cas exceptionnels dont ECLAIRE ne fait à mon sens pas partie. 



![Image](https://github.com/ansforge/IG-essais-cliniques/assets/122790741/fb9e7adc-553e-4612-94c3-1bbfb93bc4d6)




- _include 
http://hl7.org/fhir/R4/search.html#revinclude

A savoir si d'abord toutes les ressources ResearchStudy correspondant à la recherche doivent être listées et ensuite les références, je pense que c'est à l'appréciation de l'implémenteur. Le seul élément que j'ai trouvé dans la spécification est celui ci : 

![Image](https://github.com/ansforge/IG-essais-cliniques/assets/122790741/533129d5-2272-44d2-9d97-8c4f4348799b)

**Comment by paulineheurtebise** [comment]
Ok en weekly 18/09.
