### ISSUE TITLE
Contact spécifique au site

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-essais-cliniques#8]
## Description du problème

Concernant le profiling, il manque le contact spécifique au site. En effet, la ressource Location possède un champ telecom mais celui-ci ne permet pas de renseigner le nom du contact. 

## Solution proposée

Nous proposons d'ajouter une extension de type ContactDetail (qui contient les champs name et telecom).
Autre solution possible : Étendre telecom avec un champ string permettant de renseigner le nom du contact.

**Comment by nriss** [comment]
Autant réutiliser le champs telecom qui me paraît clairement adapté! Et y associer une extension

**Comment by sdemeyANS** [comment]
En attente de la validation du besoin fonctionnel

**Comment by sly-kereval** [comment]
Réunion 21/07 : 

Il semble pertinent de placer cette information dans Location.

**Comment by sly-kereval** [comment]
Question restante : L'information sur le nom du contact est-elle nécessaire ?

**Comment by sly-kereval** [comment]
> Question restante : L'information sur le nom du contact est-elle nécessaire pour le MVP ?

Réunion 27/07 : Oui

La solution proposée par Nicolas semble pertinente.
