### ISSUE TITLE
ajouter une description en anglais

### ISSUE THREAD

**Issue by sdemeyANS** [ansforge/IG-essais-cliniques#9]
## Description du problème
Il faudrait ajouter une petite description en anglais comme pour le ROR https://interop.esante.gouv.fr/ig/fhir/ror/

## Fichier•s concerné•s
index.md

## Solution proposée
comme pour le ROR https://interop.esante.gouv.fr/ig/fhir/ror/

**Comment by sly-kereval** [comment]
C'est fait sur la branche contenu_narratif_update, je lierai cette issue à la PR quand elle sera faite.
